import { useRoute } from "wouter";
import { useReport } from "@/hooks/use-reports";
import { Layout } from "@/components/layout";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { ArrowLeft, Download, FileText, CheckCircle2 } from "lucide-react";
import { Link } from "wouter";

export default function ReportView() {
  const [, params] = useRoute("/reports/:id");
  const id = params?.id ? parseInt(params.id, 10) : 0;
  
  const { data: report, isLoading } = useReport(id);

  if (isLoading) {
    return (
      <Layout>
        <div className="flex items-center justify-center h-[60vh]">
          <div className="flex flex-col items-center gap-4">
            <div className="w-12 h-12 border-4 border-primary border-t-transparent rounded-full animate-spin"></div>
            <p className="text-muted-foreground animate-pulse font-medium">Loading report document...</p>
          </div>
        </div>
      </Layout>
    );
  }

  if (!report) {
    return (
      <Layout>
        <div className="text-center p-12">
          <h2 className="text-2xl font-bold mb-4">Report Not Found</h2>
          <Link href="/reports">
            <Button variant="outline">Back to Reports</Button>
          </Link>
        </div>
      </Layout>
    );
  }

  return (
    <Layout>
      <div className="mb-6 flex items-center justify-between">
        <div className="flex items-center gap-4">
          <Link href="/reports">
            <Button variant="ghost" size="icon" className="hover:bg-white/10 rounded-full w-10 h-10">
              <ArrowLeft className="w-5 h-5" />
            </Button>
          </Link>
          <div>
            <div className="flex items-center gap-2 mb-1">
              <h1 className="text-2xl md:text-3xl font-display font-bold text-white">
                {report.country} Tax Return
              </h1>
              <CheckCircle2 className="w-5 h-5 text-emerald-500" />
            </div>
            <p className="text-muted-foreground text-sm">
              {report.period} {report.taxYear} • Generated by CAT AI
            </p>
          </div>
        </div>
        
        <div className="flex gap-3">
          <Button 
            variant="outline" 
            className="border-white/20 bg-background/50 backdrop-blur hover:bg-white/10"
            onClick={() => window.open(`/api/reports/${report.id}/download`, '_blank')}
          >
            <FileText className="w-4 h-4 mr-2" />
            Export CSV
          </Button>
          <Button 
            className="bg-primary text-primary-foreground hover:bg-primary/90 shadow-[var(--glow-primary)]"
            onClick={() => window.print()}
          >
            <Download className="w-4 h-4 mr-2" />
            Download PDF
          </Button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        <div className="col-span-1 lg:col-span-2 space-y-6">
          <Card className="glass-panel border-white/10 shadow-2xl">
            <div className="p-4 border-b border-white/10 bg-white/[0.02] flex items-center justify-between rounded-t-xl">
              <div className="font-mono text-xs text-muted-foreground flex gap-4">
                <span>OFFICIAL FORM LAYOUT</span>
                <span>STATUS: FINAL</span>
              </div>
            </div>
            <CardContent className="p-0">
              <div className="bg-[#0A0A0A] p-6 md:p-10 font-mono text-sm md:text-base text-gray-300 leading-relaxed overflow-x-auto whitespace-pre-wrap min-h-[600px] rounded-b-xl border-t border-white/5 shadow-inner">
                {report.reportText || "No text content generated yet."}
              </div>
            </CardContent>
          </Card>
        </div>
        
        <div className="col-span-1 space-y-6">
          <Card className="glass-panel border-white/10">
            <CardContent className="p-6">
              <h3 className="font-display font-bold text-lg mb-4 text-white">Report Metadata</h3>
              <div className="space-y-4">
                <div className="flex justify-between pb-3 border-b border-white/10">
                  <span className="text-muted-foreground">ID</span>
                  <span className="font-mono text-white">#{report.id}</span>
                </div>
                <div className="flex justify-between pb-3 border-b border-white/10">
                  <span className="text-muted-foreground">Jurisdiction</span>
                  <span className="text-white font-medium">{report.country}</span>
                </div>
                <div className="flex justify-between pb-3 border-b border-white/10">
                  <span className="text-muted-foreground">Tax Year</span>
                  <span className="font-mono text-white">{report.taxYear}</span>
                </div>
                <div className="flex justify-between pb-3 border-b border-white/10">
                  <span className="text-muted-foreground">Period</span>
                  <span className="text-white">{report.period}</span>
                </div>
                <div className="flex justify-between pb-3 border-b border-white/10">
                  <span className="text-muted-foreground">Status</span>
                  <span className="text-emerald-400 font-medium capitalize">{report.status}</span>
                </div>
              </div>
            </CardContent>
          </Card>

          {report.reportJson && (
            <Card className="glass-panel border-white/10">
              <CardContent className="p-6">
                <h3 className="font-display font-bold text-lg mb-4 text-white">Raw JSON Data</h3>
                <div className="bg-black/50 p-4 rounded-lg border border-white/5 overflow-hidden">
                  <pre className="text-xs font-mono text-muted-foreground overflow-x-auto max-h-[300px]">
                    {JSON.stringify(JSON.parse(report.reportJson), null, 2)}
                  </pre>
                </div>
              </CardContent>
            </Card>
          )}
        </div>
      </div>
    </Layout>
  );
}
